const { Client } = require('pg');

const client = new Client({
  connectionString: 'postgresql://postgres.zzfvtugsgupcclfhprji:75195346820abc@aws-1-us-east-2.pooler.supabase.com:5432/postgres',
});

async function run() {
  await client.connect();
  
  try {
    await client.query('BEGIN');

    const lotId = '11b96988-e4fb-4b5d-ad20-923dae2f24e2';
    const opId = '58c50aab-eb7f-46ee-93b0-164e19b16c18';
    
    // 1. Delete stock movements related to the production order (both input and output)
    console.log('Deleting stock movements related to OP...');
    await client.query(`DELETE FROM stock_movements WHERE reference_table = 'production_orders' AND reference_id = $1`, [opId]);
    
    // 2. Delete finished product lots generated by this production order
    console.log('Deleting finished product lots generated by OP...');
    await client.query(`DELETE FROM finished_product_lots WHERE production_order_id = $1`, [opId]);
    
    // 3. Delete production order milk consumptions
    console.log('Deleting production order milk consumptions...');
    await client.query(`DELETE FROM production_order_milk_consumptions WHERE production_order_id = $1`, [opId]);
    
    // 4. Delete the production order itself
    console.log('Deleting production order...');
    await client.query(`DELETE FROM production_orders WHERE id = $1`, [opId]);
    
    // 5. Delete financial entries related to the milk lot
    console.log('Deleting financial entries for milk lot...');
    await client.query(`DELETE FROM financial_entries WHERE reference_table = 'milk_lots' AND reference_id = $1`, [lotId]);
    
    // 6. Delete milk lot pricing
    console.log('Deleting milk lot pricing...');
    await client.query(`DELETE FROM milk_lot_pricing WHERE milk_lot_id = $1`, [lotId]);
    
    // 7. Delete milk lot analyses
    console.log('Deleting milk lot analyses...');
    await client.query(`DELETE FROM milk_lot_analyses WHERE milk_lot_id = $1`, [lotId]);
    
    // 8. Finally, delete the milk lot
    console.log('Deleting milk lot...');
    await client.query(`DELETE FROM milk_lots WHERE id = $1`, [lotId]);
    
    await client.query('COMMIT');
    console.log('Successfully deleted the lot and all its linked records.');
  } catch (e) {
    await client.query('ROLLBACK');
    console.error('Error during deletion, transaction rolled back:', e);
  } finally {
    await client.end();
  }
}

run().catch(console.error);
