create table if not exists milk_lot_subanalyses (
  id uuid primary key default gen_random_uuid(),
  milk_lot_analysis_id uuid not null references milk_lot_analyses(id) on delete cascade,
  compartment_number integer not null,
  analyzed_at timestamptz not null,
  alizarol text not null,
  acidez numeric(12,4),
  crioscopia numeric(12,4),
  densidade numeric(12,4),
  antibioticos text not null,
  gordura numeric(12,4),
  proteina numeric(12,4),
  cbt numeric(14,4),
  ccs numeric(14,4),
  temperatura numeric(12,4),
  alcool text,
  ph numeric(12,4),
  porcentagem_agua numeric(12,4),
  est numeric(12,4),
  esd numeric(12,4),
  redutase text,
  approved boolean not null,
  observacoes text,
  created_at timestamptz not null default now(),
  created_by uuid null,
  updated_at timestamptz not null default now(),
  updated_by uuid null,
  unique(milk_lot_analysis_id, compartment_number)
);
